services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - certs:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    profiles: ["tools"]
    image: certbot/certbot
    ports:
      - "80:80"
    volumes:
      - certs:/etc/letsencrypt

volumes:
  certs:
